### PR TITLE
FIX document and documentset permissions

### LINKED ISSUE #150: "Who can view" and "who can edit" for documents have regressed
This functionality was added in #110.

Now it doesn't seem to be working.

### PR DESCRIPTION
**Pull request by fspringveldt**
Fixes #150

### CODE REVIEW

File: code/model/DMSDocument.php [hunk 1]
```diff
@@ -1323,4 +1338,23 @@ public function getActionTaskHtml()
...
     }
+
+
+    /**
+     * Removes a single or multiple "action panel" tasks
+     *
+     * @param  string|array $panelKey
+     * @return $this
+     */
+    public function removeActionPanelTask($panelKey)
```
Comment (robbieaverill) [inline code/model/DMSDocument.php]: I think this should be single purpose. We can just call it twice and have it accept a single input each time?

File: code/model/DMSDocumentSet.php [hunk 2]
```diff
@@ -348,4 +348,56 @@ protected function validate()
...
+
+        $result = ($member &&
+            Permission::checkMember(
+                $member,
+                array('ADMIN', 'SITETREE_EDIT_ALL', 'CMS_ACCESS_DMSDocumentAdmin')
+            )
+        );
+
+        $this->extend('updateDMSDocumentSetPermissions', $result);
+        return (bool) $result;
```
Comment (robbieaverill) [inline code/model/DMSDocumentSet.php]: I think it would be better to add extension points to each of the canEdit, canView etc rather than having it here. I know it's more repetition, but it's also more extensible. e.g.

```php
$extended = $this->extendedCan(__FUNCTION__, $member);
if ($extended !== null) {
    return $extended;
}
```

Thoughts?

File: tests/DMSDocumentTest.php [hunk 3]
```diff
@@ -205,6 +222,52 @@ public function testCanEdit()
...
+        $contentAuthor = $this->objFromFixture('Member', 'editor');
+        $this->assertTrue($document1->canCreate($contentAuthor));
+    }
+
+    /**
+     * Logs out any active member
+     */
+    protected function logoutMember()
+    {
+        // Make sure user is logged out
```
Comment (robbieaverill) [inline tests/DMSDocumentTest.php]: This comment is probably not needed

File: tests/DMSDocumentTest.php [hunk 4]
```diff
@@ -205,6 +222,52 @@ public function testCanEdit()
     }
 
     /**
+     * Tests delete permissions
+     */
+    public function testCanDelete()
+    {
+        $this->logoutMember();
+        /** @var DMSDocument $document1 */
```
Comment (robbieaverill) [inline tests/DMSDocumentTest.php]: These type hints are pretty obvious, not sure if they're really that useful

**Comment by fspringveldt** [comment]
Well spotted @sachajudd. As discussed, the reason for this was not having access to the custom controller DMSDocumentAddController. This was fixed.

**Comment by robbieaverill** [comment]
>When the permissions for a user are set that their group can only view and not edit a document in the document model admin the magnifying glass action icon is clickable but the rest of the row loses its default clickable behavior.

This sounds like default GridField behaviour when you only have view access to a record. If this is the case then we shouldn't "fix" this.

File: code/model/DMSDocument.php [hunk 5]
```diff
@@ -198,6 +197,18 @@ public function canCreate($member = null)
...
 
+        // Do early admin check
+        if ($member &&
+            Permission::checkMember(
+                $member,
+                array(
+                    'CMS_ACCESS_DMSDocumentAdmin',
+                )
+            )
+        ) {
```
Comment (robbieaverill) [inline code/model/DMSDocument.php]: I must say, I'm not a big fan of spreading this code out so much - it's comfortably below the 120 character line limit recommendation without doing this

File: code/model/DMSDocumentSet.php [hunk 6]
```diff
@@ -348,4 +355,71 @@ protected function validate()
...
+     * <code>
+     * public function updateDMSDocumentSetPermissions($result)
+     * {
+     *     // Do something here
+     * }
+     * </code>
+     * @param Member $member
+     * @return bool
+     */
+    public function getDMSDocumentSetPermissions(Member $member = null)
```
Comment (robbieaverill) [inline code/model/DMSDocumentSet.php]: Given we're in the context of a DMSDocumentSet I don't see much benefit from adding that into the method naming again - using it would then mean writing `DMSDocumentSet::singleton()->getDMSDocumentSetPermissions()` over something like `DMSDocumentSet::singleton()->getPermissions()`.

Arguably it's also a single permission (yes/no) rather than permissions - maybe this method could be renamed to `getGlobalPermission` or something like that?

File: code/model/DMSDocumentSet.php [hunk 7]
```diff
@@ -348,4 +355,71 @@ protected function validate()
...
+     * Checks if a then given (or logged in) member is either an ADMIN, SITETREE_EDIT_ALL or has access
+     * to the DMSDocumentAdmin module, in which case permissions is granted.
+     *
+     * To extend use the following from within an Extension subclass:
+     *
+     * <code>
+     * public function updateDMSDocumentSetPermissions($result)
+     * {
+     *     // Do something here
+     * }
```
Comment (robbieaverill) [inline code/model/DMSDocumentSet.php]: This extension point was removed - remove the example

File: tests/DMSDocumentTest.php [hunk 8]
```diff
@@ -65,12 +67,24 @@ public function testDocumentHasCmsFieldForManagingRelatedDocuments()
...
 
     /**
+     * Ensures that the DMS Document CMS Related and Versions fields are removed if user can't edit
+     */
+    public function testDocumentHasNoCMSFieldsForManagingRelatedDocumentsIfCantEdit()
+    {
+        $this->logInWithPermission('another-user');
+        $document = $this->objFromFixture('DMSDocument', 'doc-only-these-users');
+        $gridField = $this->getGridFieldFromDocument($document);
+        $this->assertNull($gridField);
```
Comment (robbieaverill) [inline tests/DMSDocumentTest.php]: This is misleading because of the way the existing method `getGridFieldFromDocument` works - it's returning the related documents GridField but it doesn't say that in its name (my fault probably). Could you make this a bit more verbose so it's obvious that you're asserting here that the related documents GridField is null?

File: tests/DMSDocumentTest.php [hunk 9]
```diff
@@ -121,6 +134,17 @@ public function testGetActionTaskHtml()
...
+        $actions = array('example', 'embargo','find-usage');
+        foreach ($actions as $action) {
+            // Test remove with string
+            $document->removeActionPanelTask($action);
+        }
+        $result = $document->getActionTaskHtml();
+
+        $this->assertNotContains('Example', $result);
+        $this->assertNotContains('embargo', $result);
+        $this->assertNotContains('find-usage', $result);
```
Comment (robbieaverill) [inline tests/DMSDocumentTest.php]: Could you add a positive assertion here? Otherwise `removeActionPanelTask` could remove all of them and this would still pass

File: tests/DMSDocumentTest.php [hunk 10]
```diff
@@ -205,6 +222,50 @@ public function testCanEdit()
...
+    }
+
+    /**
+     * Logs out any active member
+     */
+    protected function logoutMember()
+    {
+        if ($member = Member::currentUser()) {
+            $member->logOut();
+        }
```
Comment (robbieaverill) [inline tests/DMSDocumentTest.php]: Just put this into `setUp` - there's no harm in running it for the tests that don't need it. Then you can remove its references.

File: tests/DMSDocumentTest.php (hunk 8 above)
Comment (fspringveldt) [inline tests/DMSDocumentTest.php]: Initially it was asserting yes, I've re-purposed it to, as it says, getGridFieldFromDocument and it doesn't assert anymore. The assert functionality was spread out to the individual tests.

File: tests/DMSDocumentTest.php (hunk 10 above)
Comment (fspringveldt) [inline tests/DMSDocumentTest.php]: I think let's leave it there for now. 4 out of 18 tests use this, hence I moved it out to it's own method. We're also running the risk of potentially failing 14 other tests by doing so.

File: tests/DMSDocumentTest.php (hunk 8 above)
Comment (robbieaverill) [inline tests/DMSDocumentTest.php]: Maybe just rename `getGridFieldFromDocument` to `getRelatedDocumentsGridField` so it's more clear?

File: code/cms/DMSGridFieldEditButton.php [hunk 11]
```diff
@@ -0,0 +1,25 @@
...
+    {
+        $data = new ArrayData(array(
+            'Link' => Controller::join_links($gridField->Link('item'), $record->ID, 'edit')
+        ));
+
+        $template = $record->canEdit() ? 'GridFieldEditButton' : 'GridFieldViewButton';
+
+        return $data->renderWith($template);
+    }
+}
```
Comment (robbieaverill) [inline code/cms/DMSGridFieldEditButton.php]: Better to just use `GridFieldViewButton`

File: code/model/DMSDocumentSet.php [hunk 12]
```diff
@@ -348,4 +355,65 @@ protected function validate()
...
+            return $extended;
+        }
+        return $this->getGlobalPermission($member);
+    }
+
+    /**
+     * Checks if a then given (or logged in) member is either an ADMIN, SITETREE_EDIT_ALL or has access
+     * to the DMSDocumentAdmin module, in which case permissions is granted.
+     *
+     * To extend use the following from within an Extension subclass:
```
Comment (robbieaverill) [inline code/model/DMSDocumentSet.php]: ...

File: code/cms/DMSGridFieldEditButton.php (hunk 11 above)
Comment (robbieaverill) [inline code/cms/DMSGridFieldEditButton.php]: Discussed - since this component handles individual record permissions rather than global model permissions it's good to keep
